version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    steps:
      - run: go get github.com/mattn/goveralls

      - checkout

      - run: go test -v -covermode=count -coverprofile=/tmp/coverage.out .

      - run: /go/bin/goveralls -coverprofile=/tmp/coverage.out -service circle-ci -repotoken $COVERALLS_TOKEN
